services:
  app:
    image: daredemo-design-dev
    build:
      context: ./
      dockerfile: ./develop.Dockerfile
    env_file:
      - ./.env-sample
      - ./.env
    networks:
      - daredemo-design-network
    volumes:
      - ./:/go/src/github.com/yuita-yoshihiko/daredemo-design-backend/:delegated
    depends_on:
      - db
    working_dir: /go/src/github.com/yuita-yoshihiko/daredemo-design-backend
    command: go tool air
    ports:
      - '8088:80'

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=daredemo-design_local
      - POSTGRES_PASSWORD=password
    volumes:
      - psql_data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    networks:
      - daredemo-design-network

volumes:
  psql_data:

networks:
  daredemo-design-network:
