// Package models contains generated code for schema 'public'.
package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"time"
)

// デザイン情報カテゴリー
type Category struct {
	ID        int64     `db:"id"`         // id
	Name      string    `db:"name"`       // カテゴリー名
	CreatedAt time.Time `db:"created_at"` // created_at
	UpdatedAt time.Time `db:"updated_at"` // updated_at
}
