package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"time"
)

// デザイン情報
type DesignTip struct {
	ID        int64     `db:"id"`         // id
	Title     string    `db:"title"`      // タイトル
	Guidance  string    `db:"guidance"`   // ガイダンス
	URL       string    `db:"url"`        // URL
	Media     string    `db:"media"`      // 媒体
	CreatedAt time.Time `db:"created_at"` // created_at
	UpdatedAt time.Time `db:"updated_at"` // updated_at
}
