package models

// Code generated by dbtpl. DO NOT EDIT.

// デザイン情報とカテゴリーの中間テーブル
type DesignTipCategory struct {
	DesignTipID int64 `db:"design_tip_id"` // design_tip_id
	CategoryID  int64 `db:"category_id"`   // category_id
}
